create table if not exists public.store_settings (
  key text primary key,
  value jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.store_settings enable row level security;
alter table public.orders enable row level security;

insert into public.store_settings (key, value)
values ('products', '[]'::jsonb)
on conflict (key) do nothing;

insert into public.store_settings (key, value)
values ('site_content', '{}'::jsonb)
on conflict (key) do nothing;
